### ISSUE TITLE
Error on linking: `unexpected io operation while removing clobbered file`

### ISSUE THREAD

**Issue by ruben-arts** [mamba-org/rattler#782] opened 2024-07-19 14:29 UTC
I'm getting a clobber error when I do this:
```
> rattler create sysroot_linux-64=2.12
# Succeeds
> rattler create sysroot_linux-64=2.17
Error: failed to link sysroot_linux-64-2.17-h4a8ded7_16.conda

Caused by:
    0: failed to link 'x86_64-conda-linux-gnu/sysroot/usr/share/zoneinfo'
    1: unexpected io operation while removing clobbered file
    2: Is a directory (os error 21)
```

**Comment by baszalmstra** [comment] 2024-07-24 21:16
This is a duplicate of #751

**Closed by baszalmstra** 2024-07-24 21:16 UTC
